Checkin of SAMRAI 3.7.2

diff --git a/source/test/applications/ConvDiff/Makefile.in b/source/test/applications/ConvDiff/Makefile.in
--- a/source/test/applications/ConvDiff/Makefile.in
+++ b/source/test/applications/ConvDiff/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/applications/ConvDiff
 VPATH         = @srcdir@
 TESTTOOLS     = ../../testtools
 OBJECT        = ../../../..
+REPORT        = $(OBJECT)/report.xml
 TESTINCLUDE   = $(SAMRAI)/source/test/testlib
 TESTLIBDIR    = $(OBJECT)/source/test/testlib
 TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
@@ -27,6 +28,7 @@ CPPFLAGS_EXTRA = -I$(TESTINCLUDE) -DTESTING=1
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = main.o ConvDiff.o MainRestartData.o
 F77_OBJS      = compute_rhs2d.o init2d.o rkstep2d.o tag_cells2d.o \
@@ -46,18 +48,30 @@ check:
 	$(MAKE) check3d
 
 check2d:	main
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.2d.input;
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications ConvDiff\" name=$(QUOTE)2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 check3d:	main
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.3d.input;
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications ConvDiff\" name=$(QUOTE)3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.3d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
 	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 
 examples2d: main
 	@for i in example_inputs/*.2d.input ; do	\
@@ -86,7 +100,7 @@ everything:
 clean-check:
 	$(SAMCLEAN)
 
-clean:		clean-check
+clean:	clean-check
 	$(RM) *.f main
 	$(RM) test*restart viz_*
 
@@ -105,7 +119,7 @@ compute_rhs2d.o:	$(FORTRAN)/compute_rhs2d.m4
 	$(M4) $(M4DIRS) $(FORTRAN)/compute_rhs2d.m4 > compute_rhs2d.f
 	$(F77) $(FFLAGS) -c compute_rhs2d.f -o $@
 
-init2d.o:		$(FORTRAN)/init2d.m4
+init2d.o:	$(FORTRAN)/init2d.m4
 	$(M4) $(M4DIRS) $(FORTRAN)/init2d.m4 > init2d.f
 	$(F77) $(FFLAGS) -c init2d.f -o $@
 
@@ -122,7 +136,7 @@ compute_rhs3d.o:	$(FORTRAN)/compute_rhs3d.m4
 	$(M4) $(M4DIRS) $(FORTRAN)/compute_rhs3d.m4 > compute_rhs3d.f
 	$(F77) $(FFLAGS) -c compute_rhs3d.f -o $@
 
-init3d.o:		$(FORTRAN)/init3d.m4
+init3d.o:	$(FORTRAN)/init3d.m4
 	$(M4) $(M4DIRS) $(FORTRAN)/init3d.m4 > init3d.f
 	$(F77) $(FFLAGS) -c init3d.f -o $@
 
diff --git a/source/test/nonlinear/Makefile.in b/source/test/nonlinear/Makefile.in
--- a/source/test/nonlinear/Makefile.in
+++ b/source/test/nonlinear/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/nonlinear
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check	
 
@@ -38,6 +39,7 @@ F_OBJS      =	\
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 main:	$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS)	\
@@ -48,17 +50,22 @@ check:
 
 check2d:	main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i} -skip_petscrc;	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"nonlinear\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} -skip_petscrc | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
 	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 
 examples:
 
@@ -82,7 +89,7 @@ clean-check:
 
 clean:		clean-check
 	$(RM) *.o *.f main
-	$(RM) *visit nkLog.32x32.8
+	$(RM) *visit nkLog.32x32.8 *.timing*
 
 include $(SRCDIR)/Makefile.depend
 
diff --git a/source/test/patchbdrysum/Makefile.in b/source/test/patchbdrysum/Makefile.in
--- a/source/test/patchbdrysum/Makefile.in
+++ b/source/test/patchbdrysum/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/patchbdrysum
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default:      check
 
@@ -27,6 +28,7 @@ F_OBJS       = edgeops2d.o edgeops3d.o
 NUM_TESTS = 17
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 main:	$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS) \
@@ -39,23 +41,33 @@ check:
 
 check2d:	main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"patchbdrysum\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 check3d:	main
 	@for i in test_inputs/*3d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"patchbdrysum\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest: checkcompile
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
 	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 
 examples:
 
diff --git a/source/test/performance/TreeCommunication/Makefile.in b/source/test/performance/TreeCommunication/Makefile.in
--- a/source/test/performance/TreeCommunication/Makefile.in
+++ b/source/test/performance/TreeCommunication/Makefile.in
@@ -13,8 +13,9 @@ SRCDIR	      =	@srcdir@
 SUBDIR        = source/test/performance/TreeCommunication
 VPATH	      =	@srcdir@
 OBJECT        = ../../../..
+REPORT        = $(OBJECT)/report.xml
 
-CPPFLAGS_EXTRA= -DNDIM=$(PDIM)  -DTESTING=1
+CPPFLAGS_EXTRA= -DNDIM=$(PDIM)
 
 default: check
 
@@ -23,6 +24,7 @@ include $(OBJECT)/config/Makefile.config
 NUM_TESTS = 9
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = tcb.o
 
@@ -36,22 +38,28 @@ INPUTS =	test_inputs/multiple.input	\
 		test_inputs/tlbdown.input	\
 		test_inputs/tlbL0delay.input
 
-main: $(CXX_OBJS) $(LIBSAMRAI)
+main:	$(CXX_OBJS) $(LIBSAMRAI)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) \
 	$(LIBSAMRAI) $(LDLIBS) -o $@
 
-check:		main
-		for f in $(INPUTS); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "$$f";	\
-		done
+check:	main
+	@for f in $(INPUTS); do	\
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"performance TreeCommunication\" name=$(QUOTE)$$f $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main "$$f" | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-		rm -f makecheck.logfile
-		$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-		$(OBJECT)/source/test/testtools/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
+	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
+	$(OBJECT)/source/test/testtools/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
 examples:
 
@@ -64,10 +72,10 @@ everything:
 	$(MAKE) perf
 
 clean-check:
-		$(SAMCLEAN)
+	$(SAMCLEAN)
 
 clean:
-		$(SAMCLEAN)
-		$(RM) *.f main
+	$(SAMCLEAN)
+	$(RM) *.f main
 
 include $(SRCDIR)/Makefile.depend
diff --git a/source/test/timers/Makefile.in b/source/test/timers/Makefile.in
--- a/source/test/timers/Makefile.in
+++ b/source/test/timers/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/timers
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check
 
@@ -36,16 +37,30 @@ example: main_example.o $(LIBSAMRAIDEPEND)
 NUM_TESTS = 3
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 checkcompile: timertest statstest example
 
 check:  checkcompile
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-                ./timertest test_inputs/test.input; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-                ./timertest test_inputs/test.input restart 0; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-                ./statstest 
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"timers\" name=$(QUOTE)timertest $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./timertest test_inputs/test.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"timers\" name=$(QUOTE)timertest restart $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./timertest test_inputs/test.input restart 0 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"timers\" name=$(QUOTE)statstest $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./statstest  | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 check2d:
 	$(MAKE) check
@@ -54,10 +69,10 @@ check3d:
 	$(MAKE) check
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
 	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 
 examples:
 
