Prevent race conditions in test reporting by building up two separate temporary files which are concatenated at the end.

diff --git a/source/test/dataops/Makefile.in b/source/test/dataops/Makefile.in
--- a/source/test/dataops/Makefile.in
+++ b/source/test/dataops/Makefile.in
@@ -16,6 +16,11 @@ TESTTOOLS     = ../testtools
 OBJECT        = ../../..
 REPORT        = $(OBJECT)/report.xml
 
+# These need to be built up separately to avoid race conditions when
+# writing to the report file.
+REPORT1       = $(OBJECT)/report1
+REPORT2       = $(OBJECT)/report2
+
 default: check	
 
 include $(OBJECT)/config/Makefile.config
@@ -30,6 +35,7 @@ endif
 
 TEST_NPROCS = @TEST_NPROCS@
 QUOTE = \"
+
 
 
 SampleIndexData.o:	$(SAMRAI)/source/test/dataops/SampleIndexData.C
@@ -96,6 +102,10 @@ checkcompile:   $(TARGETS2D) cell_hiertest
 
 check:
 	$(MAKE) check2d
+	cat $(REPORT1) $(REPORT2) >> $(REPORT)
+	$(RM) $(REPORT1)
+	$(RM) $(REPORT2)
+
 
 check2d:	$(SAMRAI_LIBRARY_TARGETS)
 
@@ -117,64 +127,64 @@ libdcomplex:	cell_cplxtest \
 		side_cplxtest \
 		edge_cplxtest
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT1); \
 	  $(OBJECT)/config/serpa-run $$p ./cell_cplxtest 2 | $(TEE) foo-cplx; \
-	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT1); fi; \
+	  echo "    </testcase>" >> $(REPORT1); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT1); \
 	  $(OBJECT)/config/serpa-run $$p ./cell_cplxtest 3 | $(TEE) foo-cplx; \
-	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT1); fi; \
+	  echo "    </testcase>" >> $(REPORT1); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT1); \
 	  $(OBJECT)/config/serpa-run $$p ./face_cplxtest 2 | $(TEE) foo-cplx; \
-	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT1); fi; \
+	  echo "    </testcase>" >> $(REPORT1); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT1); \
 	  $(OBJECT)/config/serpa-run $$p ./face_cplxtest 3 | $(TEE) foo-cplx; \
-	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT1); fi; \
+	  echo "    </testcase>" >> $(REPORT1); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT1); \
 	  $(OBJECT)/config/serpa-run $$p ./node_cplxtest 2 | $(TEE) foo-cplx; \
-	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT1); fi; \
+	  echo "    </testcase>" >> $(REPORT1); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT1); \
 	  $(OBJECT)/config/serpa-run $$p ./node_cplxtest 3 | $(TEE) foo-cplx; \
-	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT1); fi; \
+	  echo "    </testcase>" >> $(REPORT1); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT1); \
 	  $(OBJECT)/config/serpa-run $$p ./edge_cplxtest 2 | $(TEE) foo-cplx; \
-	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT1); fi; \
+	  echo "    </testcase>" >> $(REPORT1); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT1); \
 	  $(OBJECT)/config/serpa-run $$p ./edge_cplxtest 3 | $(TEE) foo-cplx; \
-	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT1); fi; \
+	  echo "    </testcase>" >> $(REPORT1); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT1); \
 	  $(OBJECT)/config/serpa-run $$p ./side_cplxtest 2 | $(TEE) foo-cplx; \
-	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT1); fi; \
+	  echo "    </testcase>" >> $(REPORT1); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT1); \
 	  $(OBJECT)/config/serpa-run $$p ./side_cplxtest 3 | $(TEE) foo-cplx; \
-	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT1); fi; \
+	  echo "    </testcase>" >> $(REPORT1); \
 	done; \
 	$(RM) foo-cplx
 
@@ -187,88 +197,88 @@ libdefault:	cell_patchtest \
 		edge_hiertest \
 		indx_dataops
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)indx_dataops 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)indx_dataops 2d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./indx_dataops 2 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)indx_dataops 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)indx_dataops 3d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./indx_dataops 3 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./cell_hiertest 2 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./cell_hiertest 3 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_patchtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_patchtest 2d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./cell_patchtest 2 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_patchtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_patchtest 3d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./cell_patchtest 3 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./face_hiertest 2 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./face_hiertest 3 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./node_hiertest 2 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./node_hiertest 3 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./edge_hiertest 2 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./edge_hiertest 3 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./side_hiertest 2 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT2); \
 	  $(OBJECT)/config/serpa-run $$p ./side_hiertest 3 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
-	  echo "    </testcase>" >> $(REPORT); \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT2); fi; \
+	  echo "    </testcase>" >> $(REPORT2); \
 	done; \
 	$(RM) foo
 
