remove race condition from check target when used with make -j

diff --git a/source/test/dataops/Makefile.in b/source/test/dataops/Makefile.in
--- a/source/test/dataops/Makefile.in
+++ b/source/test/dataops/Makefile.in
@@ -107,6 +107,10 @@ libchar:
 
 libfloat:
 
+# Note that tmp file names need to be distinct between targets
+# libdcomplex and libdefault to prevent race conditions using parallel
+# make.
+
 libdcomplex:	cell_cplxtest \
 		face_cplxtest \
 		node_cplxtest \
@@ -114,65 +118,65 @@ libdcomplex:	cell_cplxtest \
 		edge_cplxtest
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
 	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
-	  $(OBJECT)/config/serpa-run $$p ./cell_cplxtest 2 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  $(OBJECT)/config/serpa-run $$p ./cell_cplxtest 2 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
 	  echo "    </testcase>" >> $(REPORT); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
 	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
-	  $(OBJECT)/config/serpa-run $$p ./cell_cplxtest 3 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  $(OBJECT)/config/serpa-run $$p ./cell_cplxtest 3 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
 	  echo "    </testcase>" >> $(REPORT); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
 	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
-	  $(OBJECT)/config/serpa-run $$p ./face_cplxtest 2 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  $(OBJECT)/config/serpa-run $$p ./face_cplxtest 2 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
 	  echo "    </testcase>" >> $(REPORT); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
 	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
-	  $(OBJECT)/config/serpa-run $$p ./face_cplxtest 3 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  $(OBJECT)/config/serpa-run $$p ./face_cplxtest 3 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
 	  echo "    </testcase>" >> $(REPORT); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
 	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
-	  $(OBJECT)/config/serpa-run $$p ./node_cplxtest 2 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  $(OBJECT)/config/serpa-run $$p ./node_cplxtest 2 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
 	  echo "    </testcase>" >> $(REPORT); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
 	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
-	  $(OBJECT)/config/serpa-run $$p ./node_cplxtest 3 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  $(OBJECT)/config/serpa-run $$p ./node_cplxtest 3 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
 	  echo "    </testcase>" >> $(REPORT); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
 	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
-	  $(OBJECT)/config/serpa-run $$p ./edge_cplxtest 2 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  $(OBJECT)/config/serpa-run $$p ./edge_cplxtest 2 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
 	  echo "    </testcase>" >> $(REPORT); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
 	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
-	  $(OBJECT)/config/serpa-run $$p ./edge_cplxtest 3 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  $(OBJECT)/config/serpa-run $$p ./edge_cplxtest 3 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
 	  echo "    </testcase>" >> $(REPORT); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
 	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
-	  $(OBJECT)/config/serpa-run $$p ./side_cplxtest 2 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  $(OBJECT)/config/serpa-run $$p ./side_cplxtest 2 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
 	  echo "    </testcase>" >> $(REPORT); \
 	done
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
 	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
-	  $(OBJECT)/config/serpa-run $$p ./side_cplxtest 3 | $(TEE) foo; \
-	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  $(OBJECT)/config/serpa-run $$p ./side_cplxtest 3 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
 	  echo "    </testcase>" >> $(REPORT); \
 	done; \
-	$(RM) foo
+	$(RM) foo-cplx
 
 
 libdefault:	cell_patchtest \
