Add source term to advection equation (only used for testing). Add option to check for zero net fluxes (only used for testing). Add option to use random tagging with a specified tolerance (only used for testing). Add new input file which tests time refinement by solving with constant source term. Add new test to 2D suite in Makefile.in.

diff --git a/source/test/applications/LinAdv/Makefile.in b/source/test/applications/LinAdv/Makefile.in
--- a/source/test/applications/LinAdv/Makefile.in
+++ b/source/test/applications/LinAdv/Makefile.in
@@ -134,6 +134,12 @@ endif
 	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
 	  echo "    </testcase>" >> $(REPORT); \
 	done; \
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications LinAdv\" name=$(QUOTE)2d time refinement $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_time_refinement.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
 	$(RM) foo;
 
 check3d:	main
