Make check and checktest targets output JUnit formatted test report for use by Jenkins.
git-svn-id: https://sourceforge.llnl.gov/svn/repos/samrai_project/trunk/MASTER@1007 f45145c3-882e-4954-aa44-00140844b9ef

diff --git a/source/test/LoadBalanceCorrectness/Makefile.in b/source/test/LoadBalanceCorrectness/Makefile.in
--- a/source/test/LoadBalanceCorrectness/Makefile.in
+++ b/source/test/LoadBalanceCorrectness/Makefile.in
@@ -13,6 +13,7 @@ SRCDIR	      =	@srcdir@
 SUBDIR        = source/test/LoadBalanceCorrectness
 VPATH	      =	@srcdir@
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 TESTINCLUDE   = $(SAMRAI)/source/test/testlib
 TESTLIBDIR    = $(OBJECT)/source/test/testlib
 TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
@@ -26,6 +27,7 @@ CPPFLAGS_EXTRA= -I$(TESTINCLUDE)  -DTESTING=1
 NUM_TESTS = 24
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = main-lbcorrectness.o
 
@@ -45,14 +47,26 @@ check:
 		$(MAKE) check3d
 
 check2d:	main
-		for f in $(INPUTS2D); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "test_inputs/$$f";	\
-		done
+		@for f in $(INPUTS2D); do	\
+		  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		    echo "    <testcase classname=\"LoadBalanceCorrectness\" name=$(QUOTE)$$f $$p procs$(QUOTE)>" >> $(REPORT); \
+		    $(OBJECT)/config/serpa-run $$p ./main "test_inputs/$$f" | $(TEE) foo; \
+		    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		    echo "    </testcase>" >> $(REPORT); \
+		  done \
+		done; \
+		rm -f foo
 
 check3d:	main
-		for f in $(INPUTS3D); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "test_inputs/$$f";	\
-		done
+		@for f in $(INPUTS3D); do	\
+		  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		    echo "    <testcase classname=\"LoadBalanceCorrectness\" name=$(QUOTE)$$f $$p procs$(QUOTE)>" >> $(REPORT); \
+		    $(OBJECT)/config/serpa-run $$p ./main "test_inputs/$$f" | $(TEE) foo; \
+		    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		    echo "    </testcase>" >> $(REPORT); \
+		  done \
+		done; \
+		rm -f foo
 
 checkcompile: main
 
diff --git a/source/test/MappedBoxLevelConnectorUtilsTests/Makefile.in b/source/test/MappedBoxLevelConnectorUtilsTests/Makefile.in
--- a/source/test/MappedBoxLevelConnectorUtilsTests/Makefile.in
+++ b/source/test/MappedBoxLevelConnectorUtilsTests/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/MappedBoxLevelConnectorUtilsTests
 VPATH	      =	@srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA =  -DTESTING=1
 
@@ -24,6 +25,7 @@ include $(OBJECT)/config/Makefile.config
 NUM_TESTS = 17
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 main:	main-mblcu.o $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) main-mblcu.o $(LIBSAMRAI) $(LDLIBS) -o $@
@@ -34,14 +36,26 @@ check:		main
 	$(MAKE) check3d
 
 check2d:
-	for i in test_inputs/*.2d.input; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main $${i};	\
-	done
+	@for i in test_inputs/*.2d.input; do	\
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"MappedBoxLevelConnectorTests\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	rm -f foo
 
 check3d:
-	for i in test_inputs/*.3d.input; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main $${i};	\
-	done
+	@for i in test_inputs/*.3d.input; do	\
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"MappedBoxLevelConnectorTests\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	rm -f foo
 
 
 checkcompile: main
diff --git a/source/test/MappingConnector/Makefile.in b/source/test/MappingConnector/Makefile.in
--- a/source/test/MappingConnector/Makefile.in
+++ b/source/test/MappingConnector/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/MappingConnector
 VPATH	      =	@srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA =  -DTESTING=1
 
@@ -24,14 +25,26 @@ include $(OBJECT)/config/Makefile.config
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 main:	main-modify.o $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) main-modify.o $(LIBSAMRAI) $(LDLIBS) -o $@
 
 
 check:		main
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/modify.3blk.2d.input
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/modify.5blk.2d.input
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"MappingConnector\" name=$(QUOTE)3blks $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/modify.3blk.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"MappingConnector\" name=$(QUOTE)5blks $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/modify.5blk.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	rm -f foo
 
 check2d:
 	$(MAKE) check
diff --git a/source/test/applications/ConvDiff/Makefile.in b/source/test/applications/ConvDiff/Makefile.in
--- a/source/test/applications/ConvDiff/Makefile.in
+++ b/source/test/applications/ConvDiff/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/applications/ConvDiff
 VPATH         = @srcdir@
 TESTTOOLS     = ../../testtools
 OBJECT        = ../../../..
+REPORT        = $(OBJECT)/report.xml
 TESTINCLUDE   = $(SAMRAI)/source/test/testlib
 TESTLIBDIR    = $(OBJECT)/source/test/testlib
 TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
@@ -27,6 +28,7 @@ CPPFLAGS_EXTRA = -I$(TESTINCLUDE) -DTESTING=1
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = main.o ConvDiff.o MainRestartData.o
 F77_OBJS      = compute_rhs2d.o init2d.o rkstep2d.o tag_cells2d.o \
@@ -46,10 +48,22 @@ check:
 	$(MAKE) check3d
 
 check2d:	main
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.2d.input;
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications ConvDiff\" name=$(QUOTE)2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	rm -f foo
 
 check3d:	main
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.3d.input;
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications ConvDiff\" name=$(QUOTE)3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.3d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	rm -f foo
 
 checkcompile: main
 
diff --git a/source/test/applications/Euler/Makefile.in b/source/test/applications/Euler/Makefile.in
--- a/source/test/applications/Euler/Makefile.in
+++ b/source/test/applications/Euler/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/applications/Euler
 VPATH         = @srcdir@
 TESTTOOLS     = ../../testtools
 OBJECT        = ../../../..
+REPORT        = $(OBJECT)/report.xml
 TESTINCLUDE   = $(SAMRAI)/source/test/testlib
 TESTLIBDIR    = $(OBJECT)/source/test/testlib
 TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
@@ -27,6 +28,7 @@ CPPFLAGS_EXTRA = -I$(TESTINCLUDE) -DTESTING=1
 NUM_TESTS = 12
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = main.o Euler.o
 F_OBJS      = \
@@ -48,20 +50,82 @@ check:
 		$(MAKE) check3d
 
 check2d:	main
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.2d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.2d.input test.2d.restart 5;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync.2d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync.2d.input test_sync.2d.restart 5;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_restart.2d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_restart.2d.input test_restart.2d.restart 5
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)2d $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.2d.input | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)2d restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.2d.input test.2d.restart 5 | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)2d sync $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync.2d.input | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)2d sync restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync.2d.input test_sync.2d.restart 5 | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)2d restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_restart.2d.input | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)2d restart restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_restart.2d.input test_restart.2d.restart 5 | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done; \
+		rm -f foo
 
 check3d:	main
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.3d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.3d.input test.3d.restart 5;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync.3d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync.3d.input test_sync.3d.restart 5;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync_restart.3d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync_restart.3d.input test_sync_restart.3d.restart 5
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)3d $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.3d.input | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)3d restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.3d.input test.3d.restart 5 | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)3d sync $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync.3d.input | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)3d sync restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync.3d.input test_sync.3d.restart 5 | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)3d sync_restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync_restart.3d.input | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)3d sync_restart restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync_restart.3d.input test_sync_restart.3d.restart 5 | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done; \
+		rm -f foo
 
 checkcompile: main
 
diff --git a/source/test/applications/LinAdv/Makefile.in b/source/test/applications/LinAdv/Makefile.in
--- a/source/test/applications/LinAdv/Makefile.in
+++ b/source/test/applications/LinAdv/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/applications/LinAdv
 VPATH         = @srcdir@
 TESTTOOLS     = ../../testtools
 OBJECT        = ../../../..
+REPORT        = $(OBJECT)/report.xml
 TESTINCLUDE   = $(SAMRAI)/source/test/testlib
 TESTLIBDIR    = $(OBJECT)/source/test/testlib
 TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
@@ -43,25 +44,81 @@ check:
 		$(MAKE) check2d
 		$(MAKE) check3d
 
-# WARNING: Checking of the redistribute routine is a bit of a problem since it needs only a single run 
-#          to have been done.  So remove the old stuff.
+# WARNING: Checking of the redistribute routine is a bit of a problem since it
+#          needs only a single run  to have been done.  So remove the old
+#          stuff.
 check2d:	main
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.2d.input;
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications LinAdv\" name=$(QUOTE)2d $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.2d.input | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
 		$(RM) test.2d.restart/restore.000003/nodes.*1;
 		$(RM) test.2d.restart/restore.000003/nodes.*4;
 		$(OBJECT)/config/serpa-run 2 $(OBJECT)/tools/restart/restart-redistribute test.2d.restart test_restart_redistribute_2d 3 4;
-		$(OBJECT)/config/serpa-run 4 ./main test_inputs/test.2d.input test_restart_redistribute_2d 3;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.2d.input test.2d.restart 5;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync.2d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync.2d.input test_sync.2d.restart 5;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync_restart.2d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync_restart.2d.input test_sync_restart.2d.restart 5
+		@echo "    <testcase classname=\"applications LinAdv\" name=$(QUOTE)2d restart redistribute 4 procs$(QUOTE)>" >> $(REPORT);
+		$(OBJECT)/config/serpa-run 4 ./main test_inputs/test.2d.input test_restart_redistribute_2d 3 | $(TEE) foo;
+		@if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi;
+		@echo "    </testcase>" >> $(REPORT);
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications LinAdv\" name=$(QUOTE)2d restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.2d.input test.2d.restart 5 | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications LinAdv\" name=$(QUOTE)2d sync $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync.2d.input | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications LinAdv\" name=$(QUOTE)2d sync restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync.2d.input test_sync.2d.restart 5 | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications LinAdv\" name=$(QUOTE)2d sync_restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync_restart.2d.input | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications LinAdv\" name=$(QUOTE)2d sync_restart restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync_restart.2d.input test_sync_restart.2d.restart 5 | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done; \
+		rm -f foo;
 
 check3d:	main
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.3d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.3d.input test.3d.restart 5;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync.3d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync.3d.input test_sync.3d.restart 5
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications LinAdv\" name=$(QUOTE)3d $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.3d.input | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications LinAdv\" name=$(QUOTE)3d restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.3d.input test.3d.restart 5 | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications LinAdv\" name=$(QUOTE)3d sync $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync.3d.input | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"applications LinAdv\" name=$(QUOTE)3d sync restart $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync.3d.input test_sync.3d.restart 5 | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done; \
+		rm -f foo;
 
 checkcompile: main
 
diff --git a/source/test/async_comm/Makefile.in b/source/test/async_comm/Makefile.in
--- a/source/test/async_comm/Makefile.in
+++ b/source/test/async_comm/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/async_comm
 VPATH	      =	@srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA =  -DTESTING=1
 
@@ -24,6 +25,7 @@ include $(OBJECT)/config/Makefile.config
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 main-async_comm: main-async_comm.o $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) main-async_comm.o $(LIBSAMRAI) $(LDLIBS) -o $@
@@ -32,8 +34,19 @@ main-peer_comm: main-peer_comm.o $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) main-peer_comm.o $(LIBSAMRAI) $(LDLIBS) -o $@
 
 check:		checkcompile
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main-async_comm test_inputs/async.default.input
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main-peer_comm test_inputs/peer.default.input
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"async_comm\" name=$(QUOTE)async $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main-async_comm test_inputs/async.default.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"async_comm\" name=$(QUOTE)peer $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main-peer_comm test_inputs/peer.default.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	rm -f foo
 
 check2d:
 	$(MAKE) check
diff --git a/source/test/boundary/Makefile.in b/source/test/boundary/Makefile.in
--- a/source/test/boundary/Makefile.in
+++ b/source/test/boundary/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/boundary
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check	
 
@@ -25,6 +26,7 @@ CPPFLAGS_EXTRA= -I$(AUTOTEST) -DNDIM=$(PDIM) -DTESTING=1
 NUM_TESTS = 13
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = main.o BoundaryDataTester.o
 
@@ -38,15 +40,25 @@ check:
 
 check2d:	main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"boundary\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	   $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	rm -f foo
 
 check3d:	main
 	@for i in test_inputs/*3d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"boundary\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	rm -f foo
 
 checkcompile: main
 
diff --git a/source/test/communication/Makefile.in b/source/test/communication/Makefile.in
--- a/source/test/communication/Makefile.in
+++ b/source/test/communication/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/communication
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 TESTINCLUDE   = $(SAMRAI)/source/test/testlib
 TESTLIBDIR    = $(OBJECT)/source/test/testlib
 TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
@@ -27,6 +28,7 @@ CPPFLAGS_EXTRA= -I$(TESTINCLUDE)  -DTESTING=1
 NUM_TESTS = 56
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = \
 	CommTester.o \
@@ -55,15 +57,25 @@ check:
 
 check2d: main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"communication\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	rm -f foo
 
 check3d: main
 	@for i in test_inputs/*3d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"communication\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	rm -f foo
 
 checkcompile: main
 
diff --git a/source/test/fill_pattern/Makefile.in b/source/test/fill_pattern/Makefile.in
--- a/source/test/fill_pattern/Makefile.in
+++ b/source/test/fill_pattern/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/fill_pattern
 VPATH	      =	@srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA  = -DDISPLAY -DTESTING=1
 
@@ -24,6 +25,7 @@ include $(OBJECT)/config/Makefile.config
 NUM_TESTS = 1
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS = main-fill-pattern.o
 
@@ -33,7 +35,13 @@ main:	$(CXX_OBJS) $(LIBSAMRAIDEPEND)
 
 
 check:		main
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"fill_pattern\" name=$(QUOTE)$$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	rm -f foo
 
 check2d:
 	$(MAKE) check
diff --git a/source/test/indexdata/Makefile.in b/source/test/indexdata/Makefile.in
--- a/source/test/indexdata/Makefile.in
+++ b/source/test/indexdata/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/indexdata
 VPATH	      =	@srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 #
 # For these classes don't turn off implicit template instantiation.
@@ -32,6 +33,7 @@ main:		main.o $(LIBSAMRAIDEPEND)
 NUM_TESTS = 1
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 checkcompile: main
 
@@ -39,7 +41,13 @@ check:
 		$(MAKE) check2d
 
 check2d:	main
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"indexdata\" name=$(QUOTE)$$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done; \
+		rm -f foo
 
 check3d:
 
diff --git a/source/test/inputdb/Makefile.in b/source/test/inputdb/Makefile.in
--- a/source/test/inputdb/Makefile.in
+++ b/source/test/inputdb/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/inputdb
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check	
 
@@ -27,12 +28,18 @@ main:	inputdb.o $(LIBSAMRAIDEPEND)
 NUM_TESTS = 1
 
 TEST_NPROCS = @TEST_NPROCS@ 
+QUOTE = \"
 
 checkcompile: main
 
 check:		checkcompile
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-			./main test_inputs/inputdb.input
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"inputdb\" name=$(QUOTE)$$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main test_inputs/inputdb.input | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done; \
+		rm -f foo
 
 check2d:
 		$(MAKE) check
diff --git a/source/test/mapped_box_set_iterators/Makefile.in b/source/test/mapped_box_set_iterators/Makefile.in
--- a/source/test/mapped_box_set_iterators/Makefile.in
+++ b/source/test/mapped_box_set_iterators/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/mapped_box_set_iterators
 VPATH	      =	@srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA =  -DTESTING=1
 
@@ -24,13 +25,20 @@ include $(OBJECT)/config/Makefile.config
 NUM_TESTS = 1
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 main:	main-iterators.o $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) main-iterators.o $(LIBSAMRAI) $(LDLIBS) -o $@
 
 
 check:		main
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"mapped_box_set_iterators\" name=$(QUOTE)$$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	rm -f foo
 
 check2d:
 	$(MAKE) check
diff --git a/source/test/mblktree/Makefile.in b/source/test/mblktree/Makefile.in
--- a/source/test/mblktree/Makefile.in
+++ b/source/test/mblktree/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/mblktree
 VPATH	      =	@srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA =  -DTESTING=1
 
@@ -29,6 +30,7 @@ TEST_NPROCS = 0
 else
 TEST_NPROCS = 1
 endif
+QUOTE = \"
 
 main:	main-mbtree.o $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) main-mbtree.o $(LIBSAMRAI) $(LDLIBS) -o $@
@@ -39,14 +41,46 @@ check:		main
 	$(MAKE) check3d
 
 check2d:
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/mbtree.3blk.simple.2d.input
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/mbtree.3blk.subdivided.2d.input
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/mbtree.5blk.simple.2d.input
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/mbtree.5blk.subdivided.2d.input
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"mblktree\" name=$(QUOTE)3blks simple 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/mbtree.3blk.simple.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"mblktree\" name=$(QUOTE)3blks subdivided 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/mbtree.3blk.subdivided.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"mblktree\" name=$(QUOTE)5blks simple 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/mbtree.5blk.simple.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"mblktree\" name=$(QUOTE)5blks subdivided 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/mbtree.5blk.subdivided.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	rm -f foo
 
 check3d:
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/mbtree.full.simple.3d.input
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/mbtree.full.subdivided.3d.input
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"mblktree\" name=$(QUOTE)full simple 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/mbtree.full.simple.3d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"mblktree\" name=$(QUOTE)full subdivided 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/mbtree.full.subdivided.3d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	rm -f foo
 
 checkcompile: main
 
diff --git a/source/test/nonlinear/Makefile.in b/source/test/nonlinear/Makefile.in
--- a/source/test/nonlinear/Makefile.in
+++ b/source/test/nonlinear/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/nonlinear
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check	
 
@@ -38,6 +39,7 @@ F_OBJS      =	\
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 main:	$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS)	\
@@ -48,9 +50,14 @@ check:
 
 check2d:	main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i} -skip_petscrc;	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"nonlinear\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} -skip_petscrc | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	rm -f foo
 
 checkcompile: main
 
diff --git a/source/test/performance/LinAdv/Makefile.in b/source/test/performance/LinAdv/Makefile.in
--- a/source/test/performance/LinAdv/Makefile.in
+++ b/source/test/performance/LinAdv/Makefile.in
@@ -13,6 +13,7 @@ SRCDIR        = @srcdir@
 SUBDIR        = source/test/performance/LinAdv
 VPATH         = @top_srcdir@/$(SUBDIR)
 OBJECT        = ../../../..
+REPORT        = $(OBJECT)/report.xml
 TESTINCLUDE   = $(SAMRAI)/source/test/testlib
 TESTLIBDIR    = $(OBJECT)/source/test/testlib
 TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
@@ -25,6 +26,7 @@ CPPFLAGS_EXTRA = -I$(TESTINCLUDE)  -DTESTING=0
 
 NUM_TESTS = 2
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = main.o LinAdv.o
 F_OBJS      = \
@@ -44,10 +46,19 @@ clean:
 		$(RM) *.f main
 
 check:	main
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-			./main test_inputs/domainexpansion.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-			./main test_inputs/domainexpansionb.input;
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"performance LinAdv\" name=$(QUOTE)domainexpansion $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/domainexpansion.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"performance LinAdv\" name=$(QUOTE)domainexpansionb $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/domainexpansionb.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	rm -f foo
 
 checkcompile: main
 
diff --git a/source/test/performance/MeshGeneration/Makefile.in b/source/test/performance/MeshGeneration/Makefile.in
--- a/source/test/performance/MeshGeneration/Makefile.in
+++ b/source/test/performance/MeshGeneration/Makefile.in
@@ -13,6 +13,7 @@ SRCDIR	      =	@srcdir@
 SUBDIR        = source/test/performance/MeshGeneration
 VPATH	      =	@srcdir@
 OBJECT        = ../../../..
+REPORT        = $(OBJECT)/report.xml
 TESTINCLUDE   = $(SAMRAI)/source/test/testlib
 TESTLIBDIR    = $(OBJECT)/source/test/testlib
 TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
@@ -25,6 +26,7 @@ NUM_TESTS = 17
 CPPFLAGS_EXTRA= -I$(TESTINCLUDE)  -DTESTING=1
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = mg.o
 
@@ -64,14 +66,26 @@ check:
 check1d:	main
 
 check2d:	main
-		for f in $(INPUTS2D); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "$$f";	\
-		done
+		@for f in $(INPUTS2D); do	\
+		  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		    echo "    <testcase classname=\"performance MeshGeneration\" name=$(QUOTE)$$f $$p procs$(QUOTE)>" >> $(REPORT); \
+		    $(OBJECT)/config/serpa-run $$p ./main "$$f" | $(TEE) foo; \
+		    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		    echo "    </testcase>" >> $(REPORT); \
+		  done \
+		done; \
+		rm -f foo
 
 check3d:	main
-		for f in $(INPUTS3D); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "$$f";	\
-		done
+		@for f in $(INPUTS3D); do	\
+		  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		    echo "    <testcase classname=\"performance MeshGeneration\" name=$(QUOTE)$$f $$p procs$(QUOTE)>" >> $(REPORT); \
+		    $(OBJECT)/config/serpa-run $$p ./main "$$f" | $(TEE) foo; \
+		    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		    echo "    </testcase>" >> $(REPORT); \
+		  done \
+		done; \
+		rm -f foo
 
 checkcompile: main
 
diff --git a/source/test/performance/TreeCommunication/Makefile.in b/source/test/performance/TreeCommunication/Makefile.in
--- a/source/test/performance/TreeCommunication/Makefile.in
+++ b/source/test/performance/TreeCommunication/Makefile.in
@@ -13,6 +13,7 @@ SRCDIR	      =	@srcdir@
 SUBDIR        = source/test/performance/TreeCommunication
 VPATH	      =	@srcdir@
 OBJECT        = ../../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA= -DNDIM=$(PDIM)  -DTESTING=1
 
@@ -23,6 +24,7 @@ include $(OBJECT)/config/Makefile.config
 NUM_TESTS = 9
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = tcb.o
 
@@ -41,9 +43,15 @@ main: $(CXX_OBJS) $(LIBSAMRAI)
 	$(LIBSAMRAI) $(LDLIBS) -o $@
 
 check:		main
-		for f in $(INPUTS); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "$$f";	\
-		done
+		@for f in $(INPUTS); do	\
+		  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		    echo "    <testcase classname=\"performance TreeCommunication\" name=$(QUOTE)$$f $$p procs$(QUOTE)>" >> $(REPORT); \
+		    $(OBJECT)/config/serpa-run $$p ./main "$$f" | $(TEE) foo; \
+		    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		    echo "    </testcase>" >> $(REPORT); \
+		  done \
+		done; \
+		rm -f foo
 
 checkcompile: main
 
diff --git a/source/test/performance/treesearch/Makefile.in b/source/test/performance/treesearch/Makefile.in
--- a/source/test/performance/treesearch/Makefile.in
+++ b/source/test/performance/treesearch/Makefile.in
@@ -13,6 +13,7 @@ SRCDIR	      =	@srcdir@
 SUBDIR        = source/test/performance/treesearch
 VPATH	      =	@srcdir@
 OBJECT        = ../../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA= -DNDIM=$(PDIM)  -DTESTING=1
 
@@ -23,6 +24,7 @@ include $(OBJECT)/config/Makefile.config
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = main.o
 
@@ -36,15 +38,25 @@ check:
 
 check2d:	main
 	@for i in test_inputs/*2d*.input ; do	\
-	 $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"performance treesearch\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	rm -f foo
 
 check3d:	main
 	@for i in test_inputs/*3d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"performance treesearch\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	rm -f foo
 
 checkcompile: main
 
diff --git a/source/test/rank_group/Makefile.in b/source/test/rank_group/Makefile.in
--- a/source/test/rank_group/Makefile.in
+++ b/source/test/rank_group/Makefile.in
@@ -13,6 +13,7 @@ SRCDIR	      =	@srcdir@
 SUBDIR        = source/test/rank_group
 VPATH	      =	@srcdir@
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA= -DNDIM=$(PDIM)  -DTESTING=1
 
@@ -23,6 +24,7 @@ include $(OBJECT)/config/Makefile.config
 NUM_TESTS = 6
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = main.o
 
@@ -38,14 +40,26 @@ check:
 		$(MAKE) check3d
 
 check2d:	main
-		for f in $(INPUTS2D); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "test_inputs/$$f";	\
-		done
+		@for f in $(INPUTS2D); do	\
+		  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		    echo "    <testcase classname=\"rank_group\" name=$(QUOTE)$$f $$p procs$(QUOTE)>" >> $(REPORT); \
+		    $(OBJECT)/config/serpa-run $$p ./main "test_inputs/$$f" | $(TEE) foo; \
+		    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		    echo "    </testcase>" >> $(REPORT); \
+		  done \
+		done; \
+		rm -f foo
 
 check3d:	main
-		for f in $(INPUTS3D); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "test_inputs/$$f";	\
-		done
+		@for f in $(INPUTS3D); do	\
+		  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		    echo "    <testcase classname=\"rank_group\" name=$(QUOTE)$$f $$p procs$(QUOTE)>" >> $(REPORT); \
+		    $(OBJECT)/config/serpa-run $$p ./main "test_inputs/$$f" | $(TEE) foo; \
+		    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		    echo "    </testcase>" >> $(REPORT); \
+		  done \
+		done; \
+		rm -f foo
 
 checkcompile: main
 
diff --git a/source/test/restartdb/Makefile.in b/source/test/restartdb/Makefile.in
--- a/source/test/restartdb/Makefile.in
+++ b/source/test/restartdb/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/restartdb
 VPATH	      =	@srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA =  -DTESTING=1
 
@@ -24,6 +25,7 @@ include $(OBJECT)/config/Makefile.config
 NUM_TESTS = 5
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 testHDF5: mainHDF5.o database_tests.o $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) mainHDF5.o database_tests.o \
@@ -46,11 +48,37 @@ testMemory: mainMemory.o database_tests.o $(LIBSAMRAIDEPEND)
 	$(LIBSAMRAI) $(LDLIBS) -o testMemory
 
 check:	testHDF5 testHDF5AppFileOpen testSilo testSiloAppFileOpen testMemory
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./testHDF5
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./testHDF5AppFileOpen
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./testSilo
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./testSiloAppFileOpen
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./testMemory
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"restartdb\" name=$(QUOTE)HDF5 $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./testHDF5 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"restartdb\" name=$(QUOTE)HDF5AppFilOpen $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./testHDF5AppFileOpen | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"restartdb\" name=$(QUOTE)Silo $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./testSilo | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"restartdb\" name=$(QUOTE)SiloAppFileOpen $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./testSiloAppFileOpen | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"restartdb\" name=$(QUOTE)Memory $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./testMemory | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	rm -f foo
 
 check2d:
 	$(MAKE) check
diff --git a/source/test/sparsedata/Makefile.in b/source/test/sparsedata/Makefile.in
--- a/source/test/sparsedata/Makefile.in
+++ b/source/test/sparsedata/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/sparsedata
 VPATH	      =	@srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 #
 # For these classes don't turn off implicit template instantiation.
@@ -29,6 +30,7 @@ CPPFLAGS_EXTRA= -DTESTING=1
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 main: main.o SparseDataTester.o $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) main.o SparseDataTester.o $(LIBSAMRAI2D) $(LIBSAMRAI) $(LDLIBS) -o $@
@@ -42,8 +44,19 @@ check:
 		$(MAKE) check2d
 
 check2d:	main sparse
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./sparse
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"sparsedata\" name=$(QUOTE)main $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"sparsedata\" name=$(QUOTE)sparse $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./sparse | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	rm -f foo
 
 check3d:
 
diff --git a/source/test/timers/Makefile.in b/source/test/timers/Makefile.in
--- a/source/test/timers/Makefile.in
+++ b/source/test/timers/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/timers
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check
 
@@ -36,16 +37,30 @@ example: main_example.o $(LIBSAMRAIDEPEND)
 NUM_TESTS = 3
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 checkcompile: timertest statstest example
 
 check:  checkcompile
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-                ./timertest test_inputs/test.input; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-                ./timertest test_inputs/test.input restart 0; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-                ./statstest 
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"timers\" name=$(QUOTE)timertest $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./timertest test_inputs/test.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"timers\" name=$(QUOTE)timertest restart $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./timertest test_inputs/test.input restart 0 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"timers\" name=$(QUOTE)statstest $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./statstest  | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	rm -f foo
 
 check2d:
 	$(MAKE) check
diff --git a/source/test/transformation/Makefile.in b/source/test/transformation/Makefile.in
--- a/source/test/transformation/Makefile.in
+++ b/source/test/transformation/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/transformation
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check
 
@@ -28,11 +29,18 @@ main:  main.o $(LIBSAMRAIDEPEND)
 NUM_TESTS = 1
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 checkcompile: main
 
 check:  checkcompile
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"transformation\" name=$(QUOTE)$$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	rm -f foo
 
 check2d:
 	$(MAKE) check
diff --git a/source/test/variables/Makefile.in b/source/test/variables/Makefile.in
--- a/source/test/variables/Makefile.in
+++ b/source/test/variables/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/variables
 VPATH	      =	@srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check
 
@@ -30,6 +31,7 @@ main:	$(CXX_OBJS) $(LIBSAMRAIDEPEND)
 NUM_TESTS  = 1
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 checkcompile: main
 
@@ -38,7 +40,13 @@ check:
 		$(MAKE) check3d
 
 check2d:	checkcompile
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"variables\" name=$(QUOTE)$$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./main | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done; \
+		rm -f foo
 
 check3d:
 
diff --git a/source/test/vector/Makefile.in b/source/test/vector/Makefile.in
--- a/source/test/vector/Makefile.in
+++ b/source/test/vector/Makefile.in
@@ -14,6 +14,7 @@ SUBDIR        = source/test/vector
 VPATH	      =	@srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check
 
@@ -34,6 +35,7 @@ TEST_NPROCS = @TEST_NPROCS@
 ifeq ($(findstring 4, ${TEST_NPROCS}),4)
 TEST_NPROCS = 1,2
 endif
+QUOTE = \"
 
 check:
 		$(MAKE) check2d
@@ -42,8 +44,19 @@ check:
 check2d:
 
 check3d:	kvtest pvtest
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./kvtest
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./pvtest -skip_petscrc
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"vector\" name=$(QUOTE)kvtest $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./kvtest | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done
+		@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+		  echo "    <testcase classname=\"vector\" name=$(QUOTE)pvtest $$p procs$(QUOTE)>" >> $(REPORT); \
+		  $(OBJECT)/config/serpa-run $$p ./pvtest -skip_petscrc | $(TEE) foo; \
+		  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+		  echo "    </testcase>" >> $(REPORT); \
+		done; \
+		rm -f foo
 
 checkcompile: kvtest pvtest
 
